### PR TITLE
Support async requests for ex_roads

### PR DESCRIPTION
**Pull request by robospecta**
As per the discussion in issue 1 of the kmonline/ex_roads repo, creating a pull request in this fork to provide async support for ex_roads API wrapper.

Unable to add the issue in this fork as it appears they've been disabled. Here is the link to the original [issue](https://github.com/kmonline/ex_roads/issues/1)

### CODE REVIEW

**Comment by wevtimoteo** [comment]
Thank you for your contribution @Robospecta, I'll take a look and test it, then I can release a new version for it. Maybe we can think about implementing a test scenario or doctest for it.

**Comment by robospecta** [comment]
Sure @wevtimoteo I'm happy to do a doctest. 👍

**Comment by robospecta** [comment]
Have added a basic doctest and made some minor changes to documentation. Let me know what you think and if it's sufficient and suitable. 👍 

I also updated the pattern matching for an invalid API key in the doctests as the message from Google appears to have changed.

**Review by wevtimoteo — APPROVED** [review]
Sorry for the delay to test this one! Thank you for contribution @Robospecta :tada:

I'll release a new version for it (don't worry about tests, its missing `API_KEY`, which is already fixed in `master` branch)

**Comment by wevtimoteo** [comment]
Done! Its available under [v0.0.2](https://hex.pm/packages/google_roads/0.0.2)

**Comment by robospecta** [comment]
Thankyou so much for your help and work on this! It is appreciated 👍 💯

**Pull request merged**
